### ISSUE TITLE
allow multiple test case functions in a single file

### ISSUE THREAD

**Issue by RonakNisher** [incognito666/tarantula-python#20]
assigned to @juhidesai too

**Comment by RonakNisher** [comment]
see dcc70c79763a09d34fc4a535ea99a3c6ea46580d

@juhidesai , please do code review

**Comment by juhidesai** [comment]
code seems to be fine

**Comment by keemen90** [comment]
Not getting pass fail values from each function so your suspiciousness is not accurate.

**Comment by keemen90** [comment]
Refractor would of been too risky with a lot of code change around the core functionality. 

As a painful workaround can place test definitions in different files.
