### ISSUE TITLE
can we infuse the suspiciousness value in the generated html file?

### ISSUE THREAD

**Issue by juhidesai** [incognito666/tarantula-python#24]

**Comment by RonakNisher** [comment]
see 31f72b1704b44409af223eb4cbd156d51408497f

@juhidesai - please do code review

**Comment by juhidesai** [comment]
see 2f5323e8dd45a0dc64b28cbcba77be8aec747eae
code review done
code comments and print statements removed except printing suspiciousness values
closing the issue
